spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        #;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: password
    graphql:
        cors:
            allowed-origins: http://localhost:8080
        websocket:
            path: /graphql
        graphql:
            enabled: true
            path: /graphql
        schema:
            printer:
                enabled: true
#    data:
#        querydsl:
#            enabled: true
    jpa:
        database: h2
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
#        hibernate:
#            ddl-auto: create-drop
#            naming:
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#                #org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        show-sql: true
        properties:
            hibernate:
                format_sql: true